server {
  listen ${PORT};
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # env.js gerado em runtime pelo entrypoint (em /tmp para garantir escrita)
  location = /env.js {
    alias /tmp/env.js;
    default_type application/javascript;
    add_header Cache-Control "no-store, no-cache";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
